### ISSUE TITLE
Problem with Status: 403

### ISSUE THREAD

**Issue by Powerburningnr1** [sipgate-io/sipgateio-outgoingcall-php#1]
I have a Problem with this Script.

I get Status 403 and I don´t know why?

**Comment by mick-potzkai** [comment]
Status 403 is usually caused by a permissions problem. You might want to check the scopes of your personal access token. They should include `sessions:calls:write`. For more information about Personal Access Tokens check out our [documentation](https://www.sipgate.io/en/rest-api/authentication#personalAccessToken).
